### ISSUE TITLE
Windows eror

### ISSUE THREAD

**Issue by radulshishkov** [HydraShare/hydra-grasshopper#2]
Hydra component wouldn't work , shows Windows error 
![error](https://user-images.githubusercontent.com/39690105/40618703-01d8a96c-629b-11e8-810d-b9f1443ad961.JPG)

**Comment by chriswmackey** [comment]
@radulshishkov ,
The component could not find a Hydra forked repository on your machine. Set the Target folder input to the component to your forked hydra repository on your machine and it should work.
